### ISSUE TITLE
Error repeating

### ISSUE THREAD

**Issue by oisonan1999** [AmrDeveloper/Askme#4]
Hello!!
I am having an error that when I run the program the screen will have an error that displays information repeatedly. For example, in the friends tab, I follow 1 person but the screen shows 2 times about that person. What should I do?
![1](https://user-images.githubusercontent.com/54930174/104304003-669daa80-54fd-11eb-8a05-178396abc1bd.png)
![2](https://user-images.githubusercontent.com/54930174/104304050-74ebc680-54fd-11eb-8465-284b22098fe0.png)

**Comment by AmrDeveloper** [comment]
@oisonan1999 

Hello bro, if you have postman or and alternative try to run the request on it, 
or print the size on the log in android, 

if the result of the query is equal 3 then the problem will be from pagging code, if the result size is equal to 6 then the problem will be from the server code,

I will check the code later if you can't find the problem and I will fix it

**Comment by oisonan1999** [comment]
I test it on postman but no problem, can you fix it and push on again thank you so much !

**Comment by AmrDeveloper** [comment]
@oisonan1999 Hello, 

The bug is fixed now, it's on paging implementation, 
Thanks for reporting

BTW, I will back later to improve UI, Logger system ...etc
Thanks

**Comment by oisonan1999** [comment]
> @oisonan1999 Hello,
> 
> The bug is fixed now, it's on paging implementation,
> Thanks for reporting
> 
> BTW, I will back later to improve UI, Logger system ...etc
> Thanks

I downloaded you code you fix but it still repeat, can you see your code again?? Thank you so much

**Comment by oisonan1999** [comment]
I downloaded your code and when I run it's still repeat :(((
![image](https://user-images.githubusercontent.com/54930174/104467884-65e24280-55e9-11eb-9a04-ef9646baf21e.png)

Here is your code: 
![image](https://user-images.githubusercontent.com/54930174/104467979-7f838a00-55e9-11eb-91fa-b4f01929e256.png)
![image](https://user-images.githubusercontent.com/54930174/104468058-9aee9500-55e9-11eb-8404-600de3cc1c58.png)
![image](https://user-images.githubusercontent.com/54930174/104468104-a772ed80-55e9-11eb-88bc-0f63d91a2195.png)
![image](https://user-images.githubusercontent.com/54930174/104468141-b22d8280-55e9-11eb-9aa1-b59e0d917324.png)
![image](https://user-images.githubusercontent.com/54930174/104468197-c07b9e80-55e9-11eb-9e69-346078db9471.png)

I don't know why but it's still repeat. I really want fix this but i don't know how :((. Please help me!!!. Can you tell me what's this error

**Comment by AmrDeveloper** [comment]
@oisonan1999 Hello

In your screenshot, FeedDataSource like number 28 you will find it different from the github code check it

https://github.com/AmrDeveloper/Askme/blob/master/Android/app/src/main/java/com/amrdeveloper/askme/viewmodels/FeedDataSource.kt

you can run

git pull origin master

to pull the last code from github to your local machine

Thanks

**Comment by AmrDeveloper** [comment]
btw the bug in every data source in loadInitial function in else branch replace nextPageNum from 0 to null

so it will not repeat page 0 again
